const { PrismaClient } = require('@prisma/client')
const db = new PrismaClient()
async function main() {
  const creds = await db.credential.findMany({ select: { service: true, source: true, updatedAt: true } })
  console.log('CREDENTIALS:', JSON.stringify(creds, null, 1))
  const kw = await db.keyword.groupBy({ by: ['source'], _count: { _all: true } })
  console.log('KEYWORD SOURCES:', JSON.stringify(kw))
  const tasks = await db.task.count()
  console.log('TASKS:', tasks)
  const events = await db.systemEvent.findMany({ orderBy: { createdAt: 'desc' }, take: 15, select: { type: true, message: true, createdAt: true } })
  console.log('RECENT EVENTS:')
  events.forEach(e => console.log(`  [${e.createdAt.toISOString()}] ${e.type}: ${e.message.slice(0, 120)}`))
  const brands = await db.brand.findMany({ select: { slug: true, name: true, domain: true, status: true } })
  console.log('BRANDS:', JSON.stringify(brands))
  const integrations = await db.integration.findMany({ orderBy: { order: 'asc' }, select: { name: true, status: true, layer: true } })
  console.log('INTEGRATIONS:')
  integrations.forEach(i => console.log(`  ${i.name} [${i.layer}] = ${i.status}`))
}
main().finally(() => db.$disconnect())
